### PR TITLE
emojipicker searchBar margin fix

### PR DESCRIPTION
**Pull request by Robatortas**
Fixed margin and width of the emoji tab.
Doesn't seem to be a gif category class to fix the search bar on there tho...

### CODE REVIEW

**Comment by Gibbu** [comment]
Which part of the emojipicker does this fix? I can't seem to find any areas that are broken to warrant this.

**Comment by Robatortas** [comment]
image
It blocks the twitch emote tab.

**Comment by Gibbu** [comment]
While this would fix the twitch emotes tab it would create uncessecary spacing with it disabled.
BetterDiscord doesn't add any classes or selectors to detected if it is enabled or not so this cannot be fixed without breaking it normally.

**Comment by Robatortas** [comment]
Yeah, good point.

**Pull request closed without merging**
