### PR TITLE
Updated Class Names

### PR DESCRIPTION
**Pull request by Lioncat6**
Used this tool `https://github.com/NyxIsBad/discordscripts` to update all of the classes. Tested on my machine locally and it works!

### CODE REVIEW

**Comment by Lioncat6** [comment]
image

**Comment by Gibbu** [comment]
Absolute legend. Thank you!

**Comment by Gibbu** [comment]
Nah, that's an issue with RadialStatus itself. Since SoftX includes it with the radialglow snippet.

**Comment by Lioncat6** [comment]
Neat, time to fix that now lol

**Pull request merged**
